### ISSUE TITLE
Error in package: 'package' can only be used once per BUILD file

### ISSUE THREAD

**Issue by dzintars** [oswee/prime#13]
https://github.com/oswee/prime/commit/9982022a0e4f19d4b354c83e28bfdc293faef751
```sh
» bazel build '...'                                          
INFO: Invocation ID: a43c2fe1-4ab8-4de8-aa41-95a13df9a3f1
ERROR: Traceback (most recent call last):
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@oswee/front/BUILD.bazel", line 132, column 8, in <toplevel>
                package(default_visibility = ["//apps/front:__subpackages__"])
Error in package: 'package' can only be used once per BUILD file
ERROR: /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/BUILD.bazel:23733:11: Target '@npm//@oswee/front:front__contents' contains an error and its package is in error and referenced by '@npm//:node_modules'
ERROR: /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/BUILD.bazel:23733:11: Target '@npm//@oswee/front:front__files' contains an error and its package is in error and referenced by '@npm//:node_modules'
ERROR: /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/BUILD.bazel:23733:11: Target '@npm//@oswee/front:front__nested_node_modules' contains an error and its package is in error and referenced by '@npm//:node_modules'
ERROR: Analysis of target '//apps/front:server' failed; build aborted: Analysis failed
INFO: Elapsed time: 6.025s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (982 packages loaded, 12015 targets configured)
```

**Comment by dzintars** [comment]
Executed `bazel clean --expunge` and `bazel build '...'`.
Now getting:
```sh
» bazel build '...'    
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 5d929a6f-b73a-4dc8-84d7-2601f1c9bcfa
ERROR: /home/dzintars/code/github.com/dzintars/prime/apps/front/BUILD.bazel:20:11: in ts_library rule //apps/front:compile: 
Traceback (most recent call last):
        File "/home/dzintars/code/github.com/dzintars/prime/apps/front/BUILD.bazel", line 20, column 11, in ts_library(name = 'compile')
                ts_library(
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/build_defs.bzl", line 306, column 30, in _ts_library_impl
                ts_providers = compile_ts(
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/common/compilation.bzl", line 296, column 40, in compile_ts
                tsconfig_es6 = tsc_wrapped_tsconfig(
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/build_defs.bzl", line 244, column 29, in tsc_wrapped_tsconfig
                config = create_tsconfig(
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/common/tsconfig.bzl", line 110, column 42, in create_tsconfig
                module_mappings = get_module_mappings(ctx.label, ctx.attr, srcs = srcs)
        File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/common/module_mappings.bzl", line 102, column 29, in get_module_mappings
                fail(("all sources must be under module root: %s, but found: %s" %
Error in fail: all sources must be under module root: apps/front/src, but found: apps/front/types.d.ts
INFO: Repository remotejdk11_linux instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository zlib instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remote_java_tools_linux instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'remote_java_tools_linux' used the following cache hits instead of downloading the corresponding file.
 * Hash '0be37f4227590ecb6bc929a6a7e427c65e6239363e4c3b28b1a211718b9636c9' for https://mirror.bazel.build/bazel_java_tools/releases/javac11/v9.0/java_tools_javac11_linux-v9.0.zip
If the definition of 'remote_java_tools_linux' was updated, verify that the hashes were also updated.
ERROR: Analysis of target '//apps/front:server' failed; build aborted: Analysis failed
INFO: Elapsed time: 29.903s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1002 packages loaded, 34732 targets configured)
    Fetching /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/remote_java_tools_linux; Extracting /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/remote_java_tools_linux/java_tools_javac11_linux-v9.0.zip
```

**Comment by dzintars** [comment]
Moved types.d.ts into src directory @ 0c4598fa56160457e0417ead65fe238fed835a35
```sh
» bazel build '...'
INFO: Invocation ID: d804dd01-5661-4941-94e4-eb48c94483ed
ERROR: /home/dzintars/code/github.com/dzintars/prime/apps/front/BUILD.bazel:42:8: in _npm_package_bin rule //apps/front:bundle: label '//:index.js' in $(location) expression is not a declared prerequisite of this rule
ERROR: /home/dzintars/code/github.com/dzintars/prime/apps/front/BUILD.bazel:42:8: in args attribute of _npm_package_bin rule //apps/front:bundle: unterminated variable reference. Since this rule was created by the macro 'webpack_cli', the error might have been caused by the macro implementation
INFO: Repository remotejdk11_linux instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//apps/front:server' failed; build aborted: Analysis of target '//apps/front:bundle' failed
INFO: Elapsed time: 2.012s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (52 packages loaded, 1033 targets configured)
    Fetching @org_golang_x_text; fetching
```
