### ISSUE TITLE
YAMLException: end of the stream or a document separator is expected at line 5, column 1

### ISSUE THREAD

**Issue by dzintars** [oswee/prime#3]
When trying to commit changes getting error:
```sh
» git commit -m "chore(typescript): add basic typescript rules"
YAMLException: end of the stream or a document separator is expected at line 5, column 1:
    __metadata:
    ^
    __metadata:
    ^
    at v (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:49:12425)
    at b (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:49:12523)
    at O (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:49:25937)
    at j (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:49:26292)
    at G (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:49:26442)
    at e.exports.safeLoad (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:49:26772)
    at d (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:2:459135)
    at I (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:2:459473)
    at ie.setupResolutions (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:2:301486)
    at async Function.find (/home/dzintars/code/github.com/dzintars/prime/.yarn/releases/yarn-2.2.2.cjs:2:299697)
```
Most likely it's due to lint-staged ESLint-ing.
Tried to exclude the `.yarn` directory, but that seems does not help.

**Comment by dzintars** [comment]
https://yarnpkg.com/advanced/qa#which-files-should-be-gitignored

**Comment by dzintars** [comment]
Is that Yaml parser is trying to read JS file? Why is so?

**Comment by dzintars** [comment]
`yarn add .....` also fails

**Comment by dzintars** [comment]
OOOkk.. i cloned dzintars/prime upstream repo and repeated all the changes.
Now it does not fail.

Other thing i discovered that i have some issue:
When i run `bazel build //apps/front:index` it modifies my yarn.lock file and i can't commit die to some stale resolutions. Then i run `yarn install` and everything is fine again.
I should check what is [Self-managed npm dependencies](https://bazel.googlesource.com/rules_typescript/+/7b471a12c939d3b499f8f00746cf986629df1117/README.md#self_managed-npm-dependencies).
