### ISSUE TITLE
Error: <merged target //apps/front/src/scss:scss> doesn't contain declared provider 'DeclarationInfo'

### ISSUE THREAD

**Issue by dzintars** [oswee/prime#55]
```sh
» ibazel run //apps/front:devserver
iBazel [8:32PM]: Querying for files to watch...
Loading: 0 packages loaded
Loading: 1 packages loaded

Loading: 1 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded

Loading: 0 packages loaded
iBazel [8:32PM]: Running //apps/front:devserver
INFO: Invocation ID: 0cf1b6d9-5907-4059-bc2d-296e43aa5935
Loading:
Loading: 0 packages loaded
Analyzing: target //apps/front:devserver (0 packages loaded, 0 targets configured)
ERROR: /home/dzintars/code/github.com/dzintars/prime/apps/front/BUILD.bazel:16:11: in ts_library rule //apps/front:example:
Traceback (most recent call last):
	File "/home/dzintars/code/github.com/dzintars/prime/apps/front/BUILD.bazel", line 16, column 11, in ts_library(name = 'example')
		ts_library(
	File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/build_defs.bzl", line 306, column 30, in _ts_library_impl
		ts_providers = compile_ts(
	File "/home/dzintars/.cache/bazel/_bazel_dzintars/9d2bbefc3ec5d528aec11b4c4ea11d3f/external/npm/@bazel/typescript/internal/common/compilation.bzl", line 220, column 14, in compile_ts
		d[DeclarationInfo]
Error: <merged target //apps/front/src/scss:scss> doesn't contain declared provider 'DeclarationInfo'
ERROR: Analysis of target '//apps/front:devserver' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.118s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 28 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 28 targets configured)
iBazel [8:32PM]: Error running Bazel exit status 1
```

**Comment by dzintars** [comment]
Following this example.
Shamefully copying from - https://github.com/dataform-co/dataform/blob/master/tools/css_typings.bzl 😏 
and https://github.com/dataform-co/dataform/blob/master/app/BUILD
